-- Nimbus Direct v1 control-plane schema.
-- Runtime startup applies the equivalent idempotent schema in server/store.mjs.
CREATE TABLE customers (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL, support_email TEXT NOT NULL DEFAULT '', plan_name TEXT NOT NULL DEFAULT 'Managed infrastructure', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL) STRICT;
CREATE TABLE users (id TEXT PRIMARY KEY, customer_id TEXT REFERENCES customers(id) ON DELETE CASCADE, email TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','customer')), status TEXT NOT NULL CHECK(status IN ('active','disabled')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL) STRICT;
CREATE TABLE proxmox_clusters (id TEXT PRIMARY KEY, name TEXT NOT NULL, api_url TEXT NOT NULL, status TEXT NOT NULL, verify_tls INTEGER NOT NULL DEFAULT 1, last_sync_at INTEGER, last_error TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL) STRICT;
CREATE TABLE proxmox_credentials (id TEXT PRIMARY KEY, cluster_id TEXT NOT NULL UNIQUE REFERENCES proxmox_clusters(id) ON DELETE CASCADE, token_id TEXT NOT NULL, token_secret_encrypted TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL) STRICT;
CREATE TABLE proxmox_nodes (cluster_id TEXT NOT NULL REFERENCES proxmox_clusters(id) ON DELETE CASCADE, name TEXT NOT NULL, status TEXT NOT NULL, last_seen_at INTEGER, PRIMARY KEY(cluster_id,name)) STRICT;
CREATE TABLE resources (id TEXT PRIMARY KEY, cluster_id TEXT NOT NULL REFERENCES proxmox_clusters(id) ON DELETE CASCADE, node TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('qemu','lxc')), vmid INTEGER NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, vcpu REAL NOT NULL DEFAULT 0, memory REAL NOT NULL DEFAULT 0, memory_used REAL NOT NULL DEFAULT 0, storage REAL NOT NULL DEFAULT 0, storage_used REAL NOT NULL DEFAULT 0, cpu REAL NOT NULL DEFAULT 0, uptime INTEGER NOT NULL DEFAULT 0, ip TEXT, metadata TEXT NOT NULL DEFAULT '{}', stale INTEGER NOT NULL DEFAULT 0, last_seen_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE(cluster_id,type,vmid)) STRICT;
CREATE TABLE customer_resource_assignments (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE, resource_id TEXT NOT NULL UNIQUE REFERENCES resources(id) ON DELETE CASCADE, display_name TEXT, status TEXT NOT NULL CHECK(status IN ('active','disabled','unassigned')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL) STRICT;
CREATE TABLE assignment_permissions (assignment_id TEXT NOT NULL REFERENCES customer_resource_assignments(id) ON DELETE CASCADE, permission TEXT NOT NULL, allowed INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(assignment_id,permission)) STRICT;
CREATE TABLE sessions (id_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, csrf_token TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL) STRICT;
CREATE TABLE audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL, actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, actor_role TEXT NOT NULL, action TEXT NOT NULL, resource_id TEXT, detail TEXT NOT NULL DEFAULT '{}', ip_address TEXT, created_at INTEGER NOT NULL) STRICT;
CREATE TABLE api_tasks (id TEXT PRIMARY KEY, customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, cluster_id TEXT NOT NULL REFERENCES proxmox_clusters(id) ON DELETE CASCADE, resource_id TEXT NOT NULL, node TEXT NOT NULL, upid TEXT NOT NULL, action TEXT NOT NULL, status TEXT NOT NULL, exit_status TEXT, idempotency_key TEXT, completed_at INTEGER, last_checked_at INTEGER, created_at INTEGER NOT NULL) STRICT;
CREATE TABLE console_sessions (id_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, resource_id TEXT NOT NULL REFERENCES resources(id) ON DELETE CASCADE, ticket_encrypted TEXT NOT NULL, port INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER, created_at INTEGER NOT NULL) STRICT;
